<?php

UserModel::addSqlQuery('LISTE_PARTIES',
		'SELECT * FROM PARTIES ORDER BY DATE_CREATION');

UserModel::addSqlQuery('LISTE_PARTIES_AVEC_LOGIN',
		'SELECT * FROM PARTIE,COMPTE WHERE USER_LOGIN=:login ORDER BY GAMES_DATE_CREATION');

UserModel::addSqlQuery('COMPTE_USERS',
		'SELECT COUNT(login) FROM COMPTE');

UserModel::addSqlQuery('MEILLEURS_USERS',
		'SELECT pseudo, score FROM COMPTE ORDER BY score LIMIT 10');

UserModel::addSqlQuery('PLUS_GRAND_NOMBRE_PARTIES',
		'SELECT pseudo, SUM(nombre_victoire,nombre_defaite) AS resultat FROM COMPTE ORDER BY resultat,pseudo LIMIT 10');

UserModel::addSqlQuery('MEILLEUR_VICTOIRES',
		'SELECT pseudo, nombre_victoire FROM COMPTE ORDER BY nombre_victoire LIMIT 10');

UserModel::addSqlQuery('MEILLEUR_RATIO',
		'SELECT pseudo, IF(nombre_defaite=0, nombre_victoire, (nombre_victoire/nombre_defaite)) AS resultat FROM COMPTE ORDER BY resultat, pseudo LIMIT 10');



UserModel::addSqlQuery('DESTINATION_LES_PLUS_PIOCHEES',
		'SELECT NOM,NOMBRE_DE_FOIS_PIOCHEE FROM DESTINATION ORDER BY NOMBRE_DE_FOIS_PIOCHEE,NOM LIMIT 10');

UserModel::addSqlQuery('DESTINATION_LES_PLUS_JOUEES',
		'SELECT NOM,NOMBRE_DE_FOIS_JOUEE FROM DESTINATION ORDER BY NOMBRE_DE_FOIS_JOUEE,NOM LIMIT 10');

UserModel::addSqlQuery('NOMBRE_MOYEN_DESTINATION',
	'SELECT AVG(NOMBRE_DESTINATION_JOUEES) FROM PARTIE');

UserModel::addSqlQuery('VILLES_PLUS_JOUEES',
	'SELECT NOM FROM VILLE ORDER BY NOMBRE_DE_FOIS_JOUEE,NOM LIMIT 10');

UserModel::addSqlQuery('VILLES_MOINS_JOUEES',
	'SELECT NOM FROM VILLE ORDER BY NOMBRE_DE_FOIS_JOUEE,NOM DESC LIMIT 10');

UserModel::addSqlQuery('COULEURS_JOUEES',
	'SELECT COUNT(COULEUR) AS FROM PARTICIPANT ORDER BY COULEUR');

UserModel::addSqlQuery('NOMBRE_MOYEN_LOCOMOTIVE',
	'SELECT AVG(NOMBRE_LOCOMOTIVE_JOUEES) FROM PARTIE');


UserModel::addSqlQuery('NOMBRE_PARTIES_TERMINEES',
	'SELECT COUNT(ID_PARTIE) FROM PARTIE WHERE PARTIE_TERMINEE=1');

UserModel::addSqlQuery('NOMBRE_PARTIES_EN_COURS',
	'SELECT COUNT(ID_PARTIE) FROM PARTIE WHERE PARTIE_EN_COURS=1');

UserModel::addSqlQuery('NOMBRE_PARTIES_JOUEES',
	'SELECT COUNT(ID_PARTIE) FROM PARTIE WHERE PARTIE_JOUEE=1');

UserModel::addSqlQuery('NOMBRE_MOYEN_JOUEURS',
	'SELECT AVG(NOMBRE_DE_JOUEURS) FROM PARTIE GROUP BY ID_PARTIE');

?>